// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SecurityService.Core.Models;
using SecurityService.Infrastructure.Database;
using System;

namespace SecurityService.Infrastructure.Migrations
{
    [DbContext(typeof(SecurityDbContext))]
    [Migration("20180524115857_FixContainers")]
    partial class FixContainers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SecurityService.Core.Models.Container", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ContainerType");

                    b.Property<string>("SerialShippingContainerCode");

                    b.HasKey("Id");

                    b.ToTable("Container");
                });

            modelBuilder.Entity("SecurityService.Core.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("ContainerId");

                    b.Property<string>("Name");

                    b.Property<int>("ProductType");

                    b.HasKey("Id");

                    b.HasIndex("ContainerId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("SecurityService.Core.Models.Truck", b =>
                {
                    b.Property<string>("LicensePlate")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("ContainerId");

                    b.Property<int>("SecurityStatus");

                    b.HasKey("LicensePlate");

                    b.HasIndex("ContainerId");

                    b.ToTable("Trucks");
                });

            modelBuilder.Entity("SecurityService.Core.Models.Product", b =>
                {
                    b.HasOne("SecurityService.Core.Models.Container")
                        .WithMany("Products")
                        .HasForeignKey("ContainerId");
                });

            modelBuilder.Entity("SecurityService.Core.Models.Truck", b =>
                {
                    b.HasOne("SecurityService.Core.Models.Container", "Container")
                        .WithMany()
                        .HasForeignKey("ContainerId");
                });
#pragma warning restore 612, 618
        }
    }
}
